name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update system
      run: sudo apt update
    
    - name: Install needed deps
      run: sudo apt install -y libboost-dev libboost-filesystem-dev libconfig++-dev libsqlite3-dev ffmpeg git libjsoncpp-dev
      
    - name: Install GCC11
      shell: bash
      run: |
        sudo apt install -y gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-11 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-11
  
    - name: Configure CMake All ON
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DENABLE_HEVC=ON -DENABLE_AAC=ON -DENABLE_FDKAAC=ON \
            -DENABLE_AC3=ON -DENABLE_EAC3=ON -DENABLE_OPUS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Configure CMake All OFF
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DENABLE_HEVC=OFF -DENABLE_AAC=OFF -DENABLE_FDKAAC=OFF \
            -DENABLE_AC3=OFF -DENABLE_EAC3=OFF -DENABLE_OPUS=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update system
      run: sudo apt update

    - name: Install needed deps
      run: sudo apt install -y libboost-dev libboost-filesystem-dev libconfig++-dev libsqlite3-dev ffmpeg git libjsoncpp-dev

    - name: Install GCC11
      run: |
        sudo apt install -y gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-11 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-11

    - name: Install and run Spectral CI
      uses: checkpointsw/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --ok --include-tags base,audit3
